### ISSUE TITLE
Exponential backoff for retries?

### ISSUE THREAD

**Issue by cesarandreu** [mike-marcacci/node-redlock#10]
It'd be awesome if you supported [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) when retrying.

**Comment by mike-marcacci** [comment]
Ooh yes – that's a really great feature, definitely something to add. In my experience, each approach to retry backoff comes with its own pro/con list. To keep the redlock configs simple, I think I'd prefer accepting a user-supplied function that is called with the number of past retries, and can return the time in ms to wait (or `null` to abort). Would this work for you?

**Comment by BridgeAR** [comment]
Both, ioredis and node_redis support the described retry function. So I guess this can be handled in the used client? (I did not check how node-redlock works)

**Comment by mike-marcacci** [comment]
I've just implemented a retry jitter, which should solve the issue of contention in a more elegant way than exponential backoff. Check out https://www.awsarchitectureblog.com/2015/03/backoff.html for a good comparison.

I still have some tests to fix, but this will be out shortly, so I am going to close this issue.
