### ISSUE TITLE
[v4.2] - redis WRONGTYPE error when locking key

### ISSUE THREAD

**Issue by JojoRebondy** [mike-marcacci/node-redlock#107]
I am implementing redlock in node.js to use in combination with node's ioredis.

Whenever I try to lock a resource I get this kind of error: 

`ReplyError: ERR Error running script (call to f_0f0f23b9048b36752b5be114f357ba083449f908): @user_script:5: WRONGTYPE Operation against a key holding the wrong kind of value 
    at parseError (/media/sf_shared/wimi-core/node3/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/media/sf_shared/wimi-core/node3/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'evalsha',
    args: [
      '0f0f23b9048b36922b5be114f357ba083449f908',
      '1',
      'zmq:server:test:127.0.0.1',
      '17fd7ccf5033301e43a282f403d1a05f'
    ]
  }
}
`

I guess that redlock create a key in redis => '0f0f23b9048b36752b5be114f357ba083449f908' but Redis throw an error when the evalsha command is thrown with a WRONGTYPE error.

Any help would be gladly appreciated as I'm having a lot of troubles understanding how this could happen.

Thanks

**Comment by igorsechyn** [comment]
I was having the same issue, but in my case I solved it by prepending a resource id I was trying to lock with a prefix, smth like `locks:<resourceId>`, when passing it into `lock` method. The same id was being used elsewhere in the code as a cache key and there seemed to be a conflict.

**Comment by mike-marcacci** [comment]
Hi @JojoRebondy, I suspect @igorsechyn is right here and that you already have a key named `0f0f23b9048b36752b5be114f357ba083449f908` in redis before attempting to acquire a lock. Is this correct?

**Comment by jonaskello** [comment]
Just to add one more data point, I had the same error and it was because I already had a key with the same name.

**Comment by mike-marcacci** [comment]
Closing here, as I'm fairly sure the issue has been identified.
