### ISSUE TITLE
Custom retryCount in acquire 

### ISSUE THREAD

**Issue by xabixab** [mike-marcacci/node-redlock#121]
Hello,
I would like to thank you for this library. It is very useful.

I think it would be useful to be able to change the retryCount parameter when calling acquire overriding the configuration value. I have some tasks that must wait the lock to be released and other tasks that must fail if the resource is already locked.
Having 2 instances of redlock with diferent retryCount value seems awkward to me. Maybe I should set retryCount = 0 and program the retry on my own?

What do you think? 

Regards,
Xabier

**Comment by mike-marcacci** [comment]
Hi @xabixab,
In version 5, this should be possible: the 3rd argument to both `using` and `acquire` styles can be a partial "settings" object:

https://github.com/mike-marcacci/node-redlock/blob/606072ffdfbe1e7007f9c5e1fe40bf3fd30d0183/src/index.ts#L642-L647

https://github.com/mike-marcacci/node-redlock/blob/606072ffdfbe1e7007f9c5e1fe40bf3fd30d0183/src/index.ts#L296-L300

Hopefully this solves your use-case!

Cheers,
Mike

**Comment by xabixab** [comment]
Thank you @mike-marcacci 
It is exactly what I needed.
I will move to version 5.

Regards.
Xabier
