### ISSUE TITLE
[bug 5.0.0-beta.1] .acquire("my-key") creates a lock for every char of the string

### ISSUE THREAD

**Issue by lucasbordeau** [mike-marcacci/node-redlock#128]
The redlock.acquire() function called with a single string key creates a lock for each character of the string. 

It's a hard to debug behavior because : 

- The first error we get is something like : `ExecutionError: The operation was unable to acheive a quorum during its retry window.`
- If we dig a little bit, the error of `attempts[0].votesAgainst` map gives us an error of this kind : `ResourceLockedError: The operation was applied to: 19 of the 35 requested resources.`

To reproduce, just put a long timeout on the lock, and see in a redis client that we have a bunch of one-letter keys : 

Example : 

````typescript

const lock = await redlock.acquire("my-lock-key", 10000);
````
````redis
KEYS *
1) "-"
2) "m"
3) "y"
4) "l"
5) "o"
6) "c"
7) "k"
8) "e"
9) "y"
````

I don't know if it's intended, but the documentation + the typing of the acquire() function is misleading.

The solution is to always put the string in an array : 

````
const lock = await redlock.acquire(["my-lock-key"], 10000);
````

Methods documentation : 

````
(method) Redlock.acquire(resource: string | string[], ttl: number, callback?: Redlock.Callback<Redlock.Lock> | undefined): Bluebird<Redlock.Lock>

This method locks a resource using the redlock algorithm.

redlock.lock(
  'some-resource',       // the resource to lock
  2000,                  // ttl in ms
  function(err, lock) {  // callback function (optional)
    ...
  }
)
@param resource — one or more resources to lock

@param ttl — how long to keep the lock (milliseconds)
````

Environment :

```
"redlock": "^5.0.0-beta.1"
"@types/redlock": "^4.0.3"
```

And a single master redis server.

**Comment by shonmorgun** [comment]
```
"redlock": "^5.0.0-beta.1"
"redis": "^3.1.2"
```
I am getting the same error: `ExecutionError: The operation was unable to acheive a quorum during its retry 
window.` when calling `acquire`:
```
const lock = await redlock.acquire(['my-lock-key'], 10000);
```
@mike-marcacci can you please help?

**Comment by clouedoc** [comment]
I'm experiencing `The operation was unable to acheive a quorum during its retry window.` too and I'm on `5.0.0-beta.1` too.
Not sure if this is related to this issue.

**Comment by mike-marcacci** [comment]
Hi @lucasbordeau, this is expected as `acquire` accepts an array of resources, not a single string resource:

https://github.com/mike-marcacci/node-redlock/blob/70bc2f7b59f410a04e5626bbc5122ad36a65e6a9/src/index.ts#L296-L300

It looks like you are using version 5 (which has its own types and is native TS), along with a community-provided version of types for v4. Removing your `@types/redlock` should fix the incorrect guidance in your IDE>
