### ISSUE TITLE
Error : The operation was unable to acheive a quorum during its retry window. in release 

### ISSUE THREAD

**Issue by fzanfolim** [mike-marcacci/node-redlock#131]
Good afternoon everyone, I have the following problem.

When I lock and run a set in redis I'm trying to release the lock more than the following problem:

{"message":"The operation was unable to acheive a quorum during its retry window.","attempts":[{},{}],"name":"ExecutionError"}

Any tips?

code: 

        const lock = await this.redLock.acquire([lockId], ttl * 1000);
        let retVal;
        try {
            retVal = await func();
        } catch (e) {
            console.log(e);
        } finally {
            await lock.release();
        }

Version:
"redlock": "^5.0.0-beta.1",
"ioredis": "^4.28.2",

Node 14

**Comment by fzanfolim** [comment]
Testei tambem em outra versão mais ainda estou tendo o problema veja : 

Error: LockError: Unable to fully release the lock on resource "regression1".

Code: 

```

import Redlock from "redlock";
import IORedis from "ioredis";
import { promisify } from "util";

const client = new IORedis();
const setAsync = promisify(client.set).bind(client);

const redlock = new Redlock([client], {
  retryCount: 10,
  retryDelay: 100,
  retryJitter: 50,
});

async function main() {
  console.log("a");
  const second = await redlock.lock("regression1", 400);
  await setAsync("regression1", JSON.stringify({ message: "teste" }));
  console.log("b");
  await second.unlock();
  console.log("c");
}

main().then(console.log, console.error);

```

Version : 

"redlock": "^4.2.0",
"ioredis": "^4.28.2",
"@types/ioredis": "^4.28.5",
"@types/redlock": "^4.0.3",

Node 14

**Comment by fzanfolim** [comment]
Hey guys, I realized here where I was having problems.
The lock key was the same as the set and when unlocking the error occurred. I changed to:
'lock:key' and it works.

**Comment by gaurav-agarwal2704** [comment]
Hey @fzanfolim I am getting the same issue, but couldn't understand this : 

> The lock key was the same as the set and when unlocking the error occurred. I changed to:
'lock:key' and it works.

Can you please help me with an example ?
