### ISSUE TITLE
Is it a correct case of usage Redlock

### ISSUE THREAD

**Issue by rosendi** [mike-marcacci/node-redlock#15]
I've just read about the redlock algorithm and can't figure out is it a correct case of usage. Let's say I have a few workers and an observable which spies on some database. I use timeout to randomly pick a worker:

```
const redlock = new Redlock([...], { retryCount: 0 });

...

sub.on('message', (channel, message) => setTimeout(async () => {
  try {
    var lock = await redlock.lock('db1' /* use parsed message in the real app */, 1000);
  } catch (e) {
    console.log(e);
  }

  if (lock) {
    const watcher = new DatabaseObservable('db1').subscribe(
      message => {
        console.log(m); // something has changed in the database
      },

      err => {
        lock.unlock(); // the connection to the database was interrupted
      },

      () => {
        lock.unlock(); // the connection to the database was closed normally 
      }
    );
   
    try {
      while (1) {
        await sleep(800); // hmm... the lock here could become dead
        lock = await lock.extend(1000);
      }
    } catch (e) { ... }
  }
}, Math.random()));

sub.subscribe('watch')
```

When I need to create a new database observable I do `redis.publish('watch', 'db1')`. For each database there can be only one observable at the same time. The lock unlocks once the connection to the database is interrupted or closed. 

1. Does Redlock fit my case?

2. What is the right way here to extend locks?

3. Connections to the databases could be interrupted. So I want to recover them. Can I set an interval which repeats `Redis.publish('watch', 'db1')` unless the key is locked? Something like:

```
// in the server process around a websocket connection

setInterval(() => {
  if ( /* unlocked */) {
    redis.publish('watch', 'db1')
  }
}, 1000);

**Comment by mike-marcacci** [comment]
Hi @rosendi, to answer your questions:

1. This absolutely fits your use case!

2. Your extension logic actually looks correct, given that `lock = await lock.extend(1000);` will throw once the lock is unlocked and break the while loop. Stylistically you may want to be a bit more explicit so that it's more obvious that there won't be "deadlock" from perpetual extension, but I see nothing technically wrong with your approach:
    ```js
    // extend the lock until we are done with it
    async function extend () {
      await sleep(800);
      if (lock) {
        lock = extend();
      }
    }

    // start the extensions
    extend();

    const watcher = new DatabaseObservable('db1').subscribe(
      message => {
        console.log(m); // something has changed in the database
      },

      err => {
        lock.unlock(); // the connection to the database was interrupted
        lock = null;   // we're done with the lock, don't extend it any more
      },

      () => {
        lock.unlock(); // the connection to the database was closed normally 
        lock = null;   // we're done with the lock, don't extend it any more
      }
    );
```

3. I'm not 100% sure what you're attempting here, but generally you only have a guarantee if *you have acquired a lock*. For example, if you are on the smaller side of a network partition you will fail to acquire a lock, but you don't know if the lock exists on the other side; all you know is that you can't guarantee exclusivity on yours.

**Comment by mike-marcacci** [comment]
Actually, I take back my comment on point 2 above – the way I've written it there is the appearance of a race that would "deadlock" even though it wouldn't because `await lock.extend();` throws. I like your original strategy better, as mine doesn't really add any clarity, and further clutters the code.

**Comment by rosendi** [comment]
@mike-marcacci  Thank you for your answers!

2) That is an optimal difference between `sleep(?)` and TTL? A database observable might complete on the next process tick if a worker is busy to extend locks or because of network latency:

```
try {
  while (1) {
    await sleep(800); // 200 millis here 
    lock = await lock.extend(1000);
  }
} catch (e) { 
  watcher.complete();
}
```

Then I have to reconnect to the database but it takes non-trivial amount of time to establish a new connection.

3) It looks like it's related to https://github.com/mike-marcacci/node-redlock/issues/12, i.e. before sending a message to the workers I want to check for a lock existent.

**Comment by mike-marcacci** [comment]
2 - Setting the TTL is case-dependent. The main effects you need to consider are:

  a) deadlock recovery time: the longer the TTL, the longer the resource stays locked if your app crashes before releasing the lock, or if a network issue makes unlocking impossible
  b) exclusivity window: the sorter the TTL, the greater the risk that a network issue makes extending impossible, in which case you should stop your task if possible

Generally:

- if the resource you are locking is infrequently contested (like the ID of a task), you probably want to use longer TTL (say, a minute) and not worry about extending
- if your task keeps track of progress or can be safely paused/resumed, use a small TTL and extend frequently
- never cut an extension closer than say ~50ms, as a brief burst of open files, a large garbage collection event, or a network event _might_ add enough latency to miss your window

Your current settings seem completely sane without knowing too much about what you're doing.


3 - This is correct, and something I do frequently for a user-supplied task; however, I'd suggest also reading through #14, as I wouldn't do anything destructive assuming that a lock *is* held by another process (vs. we simply can't get a lock right now). I think I should probably add something about this to the readme.


Just out of curiosity, are working on coordination for [https://therondb.com/](therondb)? It's a really cool looking project!

**Comment by rosendi** [comment]
I really enjoy your detailed answers! Thank you.

The third issue is clear to me now: I refactored the code and now I see that knowing about lock states is useless. Back to the second issue. I have to play a little bit more with the values and finally check them with stress tests and load tests. 

Yep it's related to Theron. The final locking architecture is a bit more complicated. I can detail how database acquiring works if you are interested. I hope I'll deploy the completely refactored core and fresh docs at the end of this week. May be I open source it ...a few months ago it was just an experimental idea :-)

**Comment by rosendi** [comment]
I'm closing this issue. I've just landed a new core. Thank you again!

**Comment by mike-marcacci** [comment]
Great to hear, and no problem! I'm going to be following Theron, it's a really cool project.
