### ISSUE TITLE
Sentinel/Cluster usage?

### ISSUE THREAD

**Issue by behrad** [mike-marcacci/node-redlock#16]
For sentinel usage, can I pass a single ioredis client initialized with sentinel option?

For cluster usage, can I pass a single ioredis Cluster client?

`pass all nodes` method in documents looks ugly to me!

**Comment by mike-marcacci** [comment]
Hi @behrad, you can use sentinel and cluster behind ioredis exactly as you suggest. Do note, though, that using one cluster is subtly different from using three individual nodes when it comes to lock guarantees: while you do gain high availability and vastly increased throughput, the failure modes are a bit different, and it is theoretically possible in some configurations that a lock is acquired twice:

Assuming you are using the eventually-consistent redis replication, and you acquire a lock for a resource. Immediately after acquiring your lock, the redis master for that shard crashes. Redis does its thing and fails over to the slave which hasn't yet synced your lock. If another process attempts to acquire a lock for the same resource, it will succeed!

This is why redlock allows you to specify multiple *independent* nodes/clusters: by requiring consensus between them, we can safely take out or fail-over a minority of nodes without invalidating active locks.

While this failure scenario does sound scary (it defeats the whole point of a lock!) I've never actually seen it in practice, and for most applications it probably isn't worth worrying about. I just want to be clear about the risks! (It's easy to miss the consequences of eventual consistency in these cluster modes.)

**Comment by behrad** [comment]
Hi @mike-marcacci , thank you for your detailed answer. Why not to add the same detail in README linked to the pass all nodes config as explanation 👍

**Comment by mike-marcacci** [comment]
Great idea! Just added: 1177f54c674c78474ed8c78504de562eece0f21e
