### ISSUE TITLE
In which units should I define the driftFactor?

### ISSUE THREAD

**Issue by OrKoN** [mike-marcacci/node-redlock#17]
Is it s, ms, or relative to ttl?

Best regards,

Alex

**Comment by mike-marcacci** [comment]
Hi Alex,

Drift is in ms. I'll add that to the docs when I get a chance, but generally the default on this is going to be sufficient assuming your servers use NTP.

**Comment by OrKoN** [comment]
Thanks @mike-marcacci I have opened a pull request https://github.com/mike-marcacci/node-redlock/pull/18 

Yes, they use ntp but, for example, on AWS a misconfigured security group can block ntp traffic and then the clock jumps. So I was just wondering whether drift is in ms.
