### ISSUE TITLE
Fix Typescript types resolution

### ISSUE THREAD

**Issue by nickluger** [mike-marcacci/node-redlock#173]
The current `package.json` breaks TypeScript when used with `nodenext` (ESM) module resolution.
The `types` field in the `package.json` is no longer respected when using `exports` as this package does. See [this comment](https://github.com/microsoft/TypeScript/issues/48235#issuecomment-1067363731).

The recommended approach is to provide multiple type definition files, that should reside alongside the `js`-files, i.e.:
`./dist/esm/index.d.ts` and `./dist/cjs/index.d.cts`. The `types` field can be used as a fallback for older TS versions.

 If you have to provide a single types file, it should say instead: 

```js
 "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/esm/index.js",
      "require": "./dist/cjs/index.js"
    }
  },
```

This is explained here:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#package-json-exports-imports-and-self-referencing

**Comment by jonaskello** [comment]
I just encountered the same issue. @nickluger did you find any workaround?

**Comment by nickluger** [comment]
Ugly workaround, just add `missing-types.d.ts` or similar to your project:
```ts

// This is a temporary workaround for the following issue:
// https://github.com/mike-marcacci/node-redlock/issues/173

// just copied types
declare module "redlock" {
  /// <reference types="node" />
  import { EventEmitter } from "events";
  import { Cluster as IORedisCluster, Redis as IORedisClient } from "ioredis";

  type Client = IORedisClient | IORedisCluster;
  export type ClientExecutionResult =
    | {
        client: Client;
        vote: "against";
        error: Error;
      }
    | {
        client: Client;
        vote: "for";
        value: number;
      };
// etc, etc...
}
```
