### ISSUE TITLE
What is the correct way to know the reason why the lock was not rejected?

### ISSUE THREAD

**Issue by OrKoN** [mike-marcacci/node-redlock#19]
Hi,

I am trying to do something with Redlock (which it may not be designed for):

```
redlock
   .lock(lockResource, lockTtl)
          .then(lock => {
              // do stuff
          })
          .catch(lockErr => {
             // lockErr instanceOf redlock.LockError?
             if (technical/network error) {
               // still do stuff
             } else {
               // when the lock is created by some other process (but infrastructure is healthy)
               // do nothing
             }
          });
```

I want to know if the lock acquisition failed because someone else locked it or due to technical issues because in case of technical or network errors I want to perform the job without the lock.
What is the best way to accomplish this?

Best regards,

Alex

**Comment by mike-marcacci** [comment]
Hi @OrKoN - sorry to leave this here so long. Here's an excerpt from the readme which might be able to help:

> ### How do I check if something is locked?
> 
> Redlock cannot tell you with certainty if a resource is currently locked. For example, if you are on the smaller side of a network partition you will fail to acquire a lock, but you don't know if the lock exists on the other side; all you know is that you can't guarantee exclusivity on yours.
> 
> That said, for many tasks it's sufficient to attempt a lock with retryCount=0, and treat a failure as the resource being "locked" or (more correctly) "unavailable",

Please feel free to re-open if this doesn't answer your question!
