### ISSUE TITLE
Correct case of Redlock Usage?

### ISSUE THREAD

**Issue by ajay2611** [mike-marcacci/node-redlock#21]
I've 2 web-servers witha load balancer. I have a cron which I want to run on only one server. Can I use redlock for this?

When I used redlock like this:
```js
var resource = 'redisKey';
function getData(){

	redlock.lock(resource, ttl).then(function(lock) {
                  // logic of function
	        });
	 return lock.unlock()
        .catch(function(err) {
                   console.error(err);
     });
  });

};
```

Here, my getData function(which is part of cron for which I need lock) is working fine, but I'm not able to check if my redisKey gets SET or not. I tried commenting `lock.unlock()` but couldn't test it.
Any suggestions how can I test if my key it set by using redlock this way?

**Comment by ajay2611** [comment]
I basically want this function to be executed by one server only. So, I'm trying that whenever first server executes this cron, puts a lock on this function, so that 2nd server cannot execute this. Am I doing it right way?

**Comment by mike-marcacci** [comment]
Hi @ajay2611, it looks like you are returning too soon here, and your `lock` variable isn't in the scope of the second function; I'd definitely suggest reading up on [how promises work](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), but here's what your function should look like:

```js
var resource = 'redisKey';

function getData(){
	return redlock.lock(resource, ttl)
	.then(function(lock) {
		return Promise.resolve(logicToRun())
		.then(
			function(result) {
				// we can fire this off in the background here,
				// because we don't really care if it succeeds
				lock.unlock()
				.catch(function(errofFromUnlocking) {
					console.log(errofFromUnlocking);
				});
				
				// let's make sure to return the result  
				return result;
			},
			function(errorFromLogic) {
				// we can fire this off in the background here,
				// because we don't really care if it succeeds
				lock.unlock()
				.catch(function(errofFromUnlocking) {
					console.log(errofFromUnlocking);
				});

				// let's make sure to propagate the error
				throw errorFromLogic;
			}
		);
	});
});


function logicToRun() {
	// logic of function; it can return a promise OR a
	// resolved value, because it's called from inside
	// Promise.resolve()
}

// using your function:
getData()

// if you want something to run AFTER it's finished, chain with `then`:
.then(function(result) {
	// do something...
});
```

**Comment by ajay2611** [comment]
Thanks for a prompt reply. Implementing and testing it this way. 
By the way, is this a correct usage case of redlock algo as I've only one redis client?

**Comment by mike-marcacci** [comment]
Yep! It *can* use multiple redis instances (which provides high availability since one of 3 could go down, etc) but it's perfectly normal to have just one.

**Comment by ajay2611** [comment]
Thanks for help @mike-marcacci . Closing this issue.
