### ISSUE TITLE
Documentation clarification on `extend()`

### ISSUE THREAD

**Issue by bradvogel** [mike-marcacci/node-redlock#26]
The documentation seems to imply that `extend()` will extend the current timeout by X ms. So I'd think this would extend the lock to 15sec:

```
redlock.lock('locks:account:322456', 5000, function(err, lock) {
  lock.extend(5000, function(err, lock){
    lock.extend(5000, function(err, lock){
      // 15 secs or 5 secs?
    });
  });
});
```

But `extend()` appears to only overwrite the ttl, so it's only 5sec in the above example. This should be clarified in the docs, or `extend()` should be renamed `ttl()` since it's just resetting the ttl to a new value.

**Comment by mike-marcacci** [comment]
Hi @bradvogel - this is a really good point; I guess there are actually 3 possibilities that *could* be true given the ambiguity of the name "extend":

**1. it could extend the lock to X ms from "now"**
2. it could extend the lock to X ms from its current TTL
3. it could extend the lock by resetting its initial TTL to X

Currently, it behaves like option 1 above, although I could definitely see the utility of option 2. Just out of curiosity, do you have a use case that would favor option 2? Or is the lack of clarity your primary concern here?

**Comment by bradvogel** [comment]
Just lack of clarity. I can't think of a use case for #2.

What about renaming `extend()` to `ttl()` so it make it clearer that you're _re-setting_ the ttl. "extend" to me implies #2 above - it's extending the current value, as if you're extending a timer (as opposed to resetting it).
