### ISSUE TITLE
Could I obtain multi resource by one lock?

### ISSUE THREAD

**Issue by sunkuo** [mike-marcacci/node-redlock#28]
Hey, man,  would it be better if i can obtain multi resource by one lock . Think about this use case :  
In a shopping application , when a user place order with multi sku and count, it is a good idea to use redlock to lock the sku and judge is there enough inventory to sell.

**Comment by mike-marcacci** [comment]
Hi @sunkuo – sorry for the delay here. This is a great use case here, and I would probably recommend attempting to acquire multiple independent locks in parallel, releasing all acquired ones if one fails.

This is definitely something that is generic and probably pretty common, so if you did end up implementing this in a generic way, send a PR – it would probably make a great convenience function to redlock!

That's something I'll think about implementing as I have time!

**Comment by sunkuo** [comment]
Hello，marcacci. Nice to hear from you . I think it is realizable with the command **msetnx** and **del** . I will try implement it this week.

**Comment by mike-marcacci** [comment]
Just cleaning out old issues here; please feel free to reopen if this is still a problem, or a PR if you were able to solve this in a generic way!
