### ISSUE TITLE
Error acquiring lock: TypeError: redlock.lock is not a function

### ISSUE THREAD

**Issue by Deepanshu-Raghuwanshi** [mike-marcacci/node-redlock#302]
- Hello every one i am blocked in a error while using Redlock with  IO Redis here is my implementation .
- I am using Redlock for locking a shared resource and getting this error when trying to acquire lock.
- My IO Redis connection is getting established when app is running as i am calling 'initializeIoRedis' in app.js and i am getting this console [Connected to Redis Session Store!]
-----------------------------------------------------------------------
versions i am using

`
 "redlock": "^5.0.0-beta.2",
  "ioredis": "^5.4.1",
`
------------------------------------------------------------------------------------
Error i am getting 

Error acquiring lock: TypeError: redlock.lock is not a function
---------------------------------------------------------------------
Implementation

`const Redis = require('ioredis');
const { default: Redlock } = require('redlock');

var redisIoClient;
var redlock;

const initializeIoRedis = async () => {
  try {
    redisIoClient = new Redis({
      host: redisHost,
      port: redisPort,
      keepAlive: null,
      password: process.env.REDIS_PASSWORD,
      reconnectOnError(err) {
        if (err.code === 'ETIMEDOUT') {
          return true;
        }
      },
    });

    redlock = new Redlock([redisIoClient], {
      driftFactor: 0.01,
      retryCount: 50,
      retryDelay: 3500,
      retryJitter: 200,
      automaticExtensionThreshold: 1000,
    });

    redlock.on('error', (error) => {
      // Ignore cases where a resource is explicitly marked as locked on a client.
      if (error instanceof ResourceLockedError) {
        return;
      }

      // Log all other errors.
      console.error(error);
    });

    // Listen to 'error' events to the Redis connection
    redisIoClient.on('error', (error) => {
      if (error.code === 'ECONNRESET') {
        console.log('Connection to Redis Session Store timed out.');
      } else if (error.code === 'ECONNREFUSED') {
        console.log('Connection to Redis Session Store refused!');
      } else console.log(error);
    });

    // Listen to 'reconnecting' event to Redis
    redisIoClient.on('reconnecting', (err) => {
      if (redisIoClient.status === 'reconnecting')
        console.log('Reconnecting to Redis Session Store...');
      else console.log('Error reconnecting to Redis Session Store.');
    });

    // Listen to the 'connect' event to Redis
    redisIoClient.on('connect', (err) => {
      if (!err) console.log('Connected to Redis Session Store!');
    });
  } catch (error) {
    console.log('Error initializing IO Redis:', error);
  }
};

// Function to acquire a lock.
// ttl for time to live lock.
async function acquireLock(resource, ttl) {
  if (!redlock) {
    console.error('Redlock is not initialized. Cannot acquire lock.');
    return null;
  }
  try {
    const lock = await redlock.lock(resource, ttl);
    console.log(`Lock acquired for resource: ${resource}`);
    return lock;
  } catch (error) {
    console.error('Error acquiring lock:', error);
    return null;
  }
}

// // Function to release a lock
async function releaseLock(lock) {
  try {
    await lock.unlock();
    console.log('Lock released');
  } catch (error) {
    console.error('Error releasing lock:', error);
  }
}`

 

@mike-marcacci  sir need your help

**Comment by dillonstreator** [comment]
@Deepanshu-Raghuwanshi - this doesn't provide enough context to troubleshoot the issue. Given you have a global variable `redlock` that is initially `undefined`, it's quite possible that `acquireLock` is being called before `initializeIoRedis` is finished and `redlock` is initialized.

Could you share a minimally reproducible example repository, including the code that calls these functions?

<details>
<summary>Formatted Redis and Redlock Initialization Code</summary>

```js
const Redis = require('ioredis');
const { default: Redlock } = require('redlock');

var redisIoClient;
var redlock;

const initializeIoRedis = async () => {
  try {
    redisIoClient = new Redis({
      host: redisHost,
      port: redisPort,
      keepAlive: null,
      password: process.env.REDIS_PASSWORD,
      reconnectOnError(err) {
        if (err.code === 'ETIMEDOUT') {
          return true;
        }
      },
    });

    redlock = new Redlock([redisIoClient], {
      driftFactor: 0.01,
      retryCount: 50,
      retryDelay: 3500,
      retryJitter: 200,
      automaticExtensionThreshold: 1000,
    });

    redlock.on('error', (error) => {
      // Ignore cases where a resource is explicitly marked as locked on a client.
      if (error instanceof ResourceLockedError) {
        return;
      }

      // Log all other errors.
      console.error(error);
    });

    // Listen to 'error' events to the Redis connection
    redisIoClient.on('error', (error) => {
      if (error.code === 'ECONNRESET') {
        console.log('Connection to Redis Session Store timed out.');
      } else if (error.code === 'ECONNREFUSED') {
        console.log('Connection to Redis Session Store refused!');
      } else console.log(error);
    });

    // Listen to 'reconnecting' event to Redis
    redisIoClient.on('reconnecting', (err) => {
      if (redisIoClient.status === 'reconnecting')
        console.log('Reconnecting to Redis Session Store...');
      else console.log('Error reconnecting to Redis Session Store.');
    });

    // Listen to the 'connect' event to Redis
    redisIoClient.on('connect', (err) => {
      if (!err) console.log('Connected to Redis Session Store!');
    });
  } catch (error) {
    console.log('Error initializing IO Redis:', error);
  }
};

// Function to acquire a lock.
// ttl for time to live lock.
async function acquireLock(resource, ttl) {
  if (!redlock) {
    console.error('Redlock is not initialized. Cannot acquire lock.');
    return null;
  }
  try {
    const lock = await redlock.lock(resource, ttl);
    console.log(`Lock acquired for resource: ${resource}`);
    return lock;
  } catch (error) {
    console.error('Error acquiring lock:', error);
    return null;
  }
}

// Function to release a lock
async function releaseLock(lock) {
  try {
    await lock.unlock();
    console.log('Lock released');
  } catch (error) {
    console.error('Error releasing lock:', error);
  }
}
```

</details>

**Comment by Deepanshu-Raghuwanshi** [comment]
@dillonstreator thanx for replying but it is sorted
