### ISSUE TITLE
2.1.1 broken, never lock resolved

### ISSUE THREAD

**Issue by darky** [mike-marcacci/node-redlock#31]
```javascript
locker.lock(resource, ttl).then(_ => {
  // this code never called
})
```

**Comment by mike-marcacci** [comment]
Hey @darky - two questions:

1. was this working before 2.1.1 or is this a new use case?
2. what are your retry settings?

**Comment by darky** [comment]
1. This working in 2.1.0
2. Any settings
3. Yes
4. I use bluebird promise, maybe this case problematic?

**Comment by mike-marcacci** [comment]
OK, I've spent some time diving into this an I have a suspicion: this patch changed some implementation details to prevent lockups under high contention by adding a jitter to the retry logic. The API remained the same, so a non-breaking semver change seemed appropriate.

However, if you have a timeout or similar logic racing the lock, this change would have introduced more variability to the retry times.

I've deprecated the version 2.1.1 on NPM, added some test targets and re-released it as 3.0.0.

Can you try again with 3.0.0, but in addition to specifying your `retryCount` and `retryDelay`, try setting `retryJitter` to zero.

**Comment by darky** [comment]
`3.0.0` all :+1:

**Comment by schmod** [comment]
2.1.1 does not appear to have been deprecated?

**Comment by schmod** [comment]
Actually, nevermind.  NPM deprecations are virtually invisible.  `^2.1.0` will still install `2.1.1`, and will dump a tiny warning into the middle of NPM's (very verbose) output.

**Comment by mike-marcacci** [comment]
Hi @schmod, yes - I wish it were a bit better. Sadly, [depricate](https://docs.npmjs.com/cli/deprecate) is a bit too soft, while [unpublish](https://docs.npmjs.com/cli/unpublish) is far too heavy-handed (and also not an option, since it has been > 24 hours since publication).

**Comment by schmod** [comment]
maybe publish a `2.1.2` that essentially reverts back to `2.1.0`?

**Comment by mike-marcacci** [comment]
Done! Excellent idea – don't know why I didn't think of this early.

**Comment by schmod** [comment]
Awesome!  Thanks!
