### ISSUE TITLE
is it possible to expose attempts with redlock.attempts

### ISSUE THREAD

**Issue by FoghostCn** [mike-marcacci/node-redlock#33]
I want to know how many times it retried until get the lock, so  is it possible to expose it to lock instance

**Comment by mike-marcacci** [comment]
Hi @FoghostCn, that’s a really cool idea, and while no such feature currently exists, I would definitely be OK adding it.

I do have a couple clarifying questions though: in a scenario where redlock is used with multiple redis instances or clusters, it is possible for a minority to fail, and for those which succeed to do so on different attempts. For example:

- *Node 1* unavailable
- *Node 2* succeeds on 2nd attempt
- *Node 3* succeeds on 3rd attempt

Do you have any preference on how you would want this represented?

**Comment by FoghostCn** [comment]
I mean how many times it had retried,just like `retryCount`.
