### ISSUE TITLE
Execute Exactly Once, Execute At Least Once?

### ISSUE THREAD

**Issue by tomercagan** [mike-marcacci/node-redlock#34]
Hi,

First - even though I haven't used this module yet, I want to thank for the work and support you're giving here . I really think it is great!

Now, I have this scenario where I have a scheduler in my app that execute scheduled tasks (or cron jobs). This scheduler is part of the app (I know, bad design, but that's what I currently have), so once I start the instance, I also get the scheduler running.

In one-node scenario this works fine. Now I want to scale up, and as a quick-fix, I though to use redlock, though I am not sure I can really get the right "guarantees".

I have read issues discussing similar requirements/concerns (e.g. #15, #19, and #21 which is similar) but still not 100% sure how I should implement this. Mainly around retries and errors that are reported.

My initial thought is to use 0 retries, that why, given a task T1 to be executed (at some time t), 

* If the worker, W1, managed to lock - it execute the T1
* If the worker, W1, didn't managed to lock, it doesn't do anything (0-retries)

But I think this will not guarantee that the task will be executed. 

Failure to get the lock (if I understand correctly) could mean that either some other worker got the lock before (and W1 should not do the work), or W1 has some error (e.g. didn't get quorum because it is in a "smaller" side of a partition), and should retry.

Is there a way to implement a "Execute Exactly Once" logic with RedLock alone or maybe I should resort to using some additional state and allow retries?

An example of the above would be to save an execution log/state that once the worker got a lock, it will check against and return if there's a log entry indicating the work was executed. 

Note that in this way, the critical section would include the work, and the update of the log. In such implementation, a case of many workers competing for a task with several retries means 1 worker will do the actual work and N-1 workers will try to acquire the lock until they succeed and do nothing once they have the lock.

Thanks (again, and in advance! ;-))

**Comment by mike-marcacci** [comment]
Hi @tomercagan,

It sounds like you have a pretty good read on how this works! The quick answer is that you'll need to store state somewhere else. Here's the longer answer:

You have a task that needs to be completed exactly once. This means that you have to account for failure at any stage of the task – even failures of the entire system (somebody might trip over the power cable). Let's break this down into its two parts:

### The task must not complete MORE than once:

- If a task has been complete, we must not start it again
- **If a task has been started, we must not start it again until we know whether it has completed or failed**

### The task must not complete LESS than once:

- If a task is created, it must start
- If a task fails:
    + In the simplest cases, we can simply restart it
    + If we keep "checkpoints" (divided it into smaller tasks) we can resume from the last complete sub-task
    + If the task has side effects, we may need to revert and re-run, etc

There's a lot of other conditions/scenarios I could add above, but this hopefully illustrates the kinds of use case you have. In this scenario, redlock is only concerned with the problem in bold. While it's a very good solution to that problem, it doesn't provide much for addressing the other problems.

More generically, it's concerned with ensuring exclusivity in a distributed environment. Hopefully that helps – and free to follow up with more questions!

Cheers,
Mike

**Comment by mike-marcacci** [comment]
Hi @tomercagan,

I'm going to close this issue. Please feel free to reopen if you have further questions.
