### ISSUE TITLE
What type of locking? read lock, write lock or?

### ISSUE THREAD

**Issue by WinMinTun** [mike-marcacci/node-redlock#35]
I have read https://redis.io/topics/distlock , still not clear what kind of locking it is. Could u shed me some light? Is it read lock/write lock or absolute lock where other party can do nth but wait?

**Comment by mike-marcacci** [comment]
I answered this briefly [in your other question](https://github.com/mike-marcacci/node-redlock/issues/36#issuecomment-352197723), but I'll reiterate it here with a bit more detail:

Redlock is about guaranteeing *exclusivity* in a distributed environment, and that's pretty much it. You likely don't need it for purely read-only operations, but there may a use case I haven't thought of. 

For example, let's say you have a user who had a "balance." The user wants to buy something, but you first need to check that she has a sufficient balance! The problem with a naive implementation is that she might execute orders very quickly apart, and you would have a race condition: both orders see the original balance, and proceed even though together their amounts might be greater than the original balance!

In a distributed system, this can be very challenging, especially if you don't control all aspects of the pipeline. Redlock can be used to force the second order to wait until the first is done, before being attempted.

Hopefully that helps!

**Comment by WinMinTun** [comment]
@mike-marcacci Thank you so much. It is a very nice module and support. Appreciate it

**Comment by oallouch** [comment]
Hi, I'm new to this lib and was looking for a ReadWriteLock on node.js . I guess I'll use a simple lock :)
Anyway, this lib saves me.
Thx

Btw, here's a lib in Java that does it all : https://github.com/redisson/redisson
