### ISSUE TITLE
Redlock performance under high contention

### ISSUE THREAD

**Issue by WinMinTun** [mike-marcacci/node-redlock#37]
Hi @mike-marcacci,

I tried to understand the redlock performance under high contention, still don't really understand. So I would be grateful if you could help me understand. I m developing a real-time collaborative writing like Google Word. In that system we have a number of NodeJS servers, and when a new user comes to the system (connected to one of the NodeJS servers), we assign unique authorship color.

During that time, no matter the nodejs server, need to access the same few Redis entries to determine color. During that particular time, these Redis entries have to be RedLocked from other servers. 

So let's say, if 1000 users connect to different NodeJS servers at the same time, with the Redlock on the same Redis entries, do you have some idea on Redlock performance? (each connection takes ~14 milliseconds). It is also very difficult to test concurrency :(

Thank you so much, really appreciate it.

**Comment by mike-marcacci** [comment]
Hi @WinMinTun, sorry for the slow reply. Reading through your use case here, this definitely sounds like a scenario where I would use redlock or something like it. As you mention, the performance is is effected by myriad variables. Some of these are:

- network latency
- the specs of your redis server
- the load on your redis server from other calls
- the length of time each lock must be held
- the retry delay you use
- the number of servers/clusters used (the more copies exist, the greater the probability of a round not leading to consensus, essentially wasting the time it took for that election)

Honestly, it's very difficult to give you an estimate of how something will perform in a given situation, and the best thing to do will be to test it! I'd suggest running a simple script to see how long it takes 1000 acquisitions, and tweak your settings accordingly.

One thing I would like to note, is that fundamentally, whenever you require exclusivity, you are making all these requests sequential, and the best possible scenario using any technology is the average duration of the job multiplied by the number of concurrent jobs. So redlock aside, if it takes you 20ms to come up with a color and save it somewhere, it's going to take 20 seconds for all 1000 contending users to get a color.

Regardless if you use redlock or not, I would probably recommend using some strategy to minimize the amount of contention here. For example, you might:

1. only make colors unique per "room" or "document" etc
2. pick a color *first* and use a lock to keep others from using that same color for the duration of the lock

```es6
// there's no point in retrying if we fail – we'll just generate a different random number and try again!
const redlock = new Redlock([client1, client2, client3], {retryCount: 0});

// we will hold colors per room for up to an hour after we haven't heard from the user
const ttl = 1000 * 60 * 60;

async function getUserColor (roomId) {
	const color = generateRandomRGB(); // generates a hex value, for example
	const lock = await redlock.lock(`locks:colors:${roomId}:${color}`, ttl);
	return { color, lock };
}
```

This way it's **extremely unlikely** that you'll have heavy contention, but you'll be protected against duplicates. You can extend the lock every time the user does something that lets you know she's still in the room, and then just let it expire after she's no longer active.

Finally, if you want to prevent "similar" colors, you may want to simply limit the colors your generator can generate.

Hope that helps!

**Comment by mike-marcacci** [comment]
EDIT: I made a couple changes to the above example code; Also do note that I'd probably recommend a timeout or max number of failed attempts or some other escape hatch to avoid infinite recursion.

**Comment by mike-marcacci** [comment]
Hey @WinMinTun, I'm going to go ahead and close this issue, but feel free to reopen if you have further questions about performance or fitness of redlock for a particular application!

**Comment by WinMinTun** [comment]
@mike-marcacci Very sorry. I forget to close. Your explanation really helpful. Later after production and I encounter things, I would share the locking experience here. Thanks for the amazing piece of work!

**Comment by mike-marcacci** [comment]
Absolutely! Cheers!
