### ISSUE TITLE
Unlock error with string_numbers=true

### ISSUE THREAD

**Issue by Wiezzel** [mike-marcacci/node-redlock#39]
There is an option `string_numbers` in Redis client (ref: https://github.com/NodeRedis/node_redis#options-object-properties) to return number values as strings.

Node-redlock is incompatible with this option because it expects the response to be always a number: https://github.com/mike-marcacci/node-redlock/blob/master/redlock.js#L203. In result, setting `string_numbers` to `true` causes an error in Redlock.unlock(): `LockError: Unable to fully release the lock on resource`.

**Comment by mike-marcacci** [comment]
Thanks for the great report! This has been fixed and published as `3.1.1`.
