### ISSUE TITLE
lock is not defined when redis client is locally bound

### ISSUE THREAD

**Issue by nathansizemore** [mike-marcacci/node-redlock#5]
~~~javascript
var redisClient = redis.createClient();
    var redlock = new Redlock({
        driftFactor: 0.01,
        retryCount: 225,
        retryDelay: 250
    }, redisClient);

redlock.lock(LOCK_PUBLIC_LIST, LOCK_TIME, function(error, lock) {
    if (error) {
        console.log(error);
    }
});
~~~

Will produce the error: `TypeError: undefined is not a function`

If create client is made with a public facing IPv4 and port, it works every time

**Comment by mike-marcacci** [comment]
Hi @nathansizemore, I first just want to confirm: it looks like you're using version 0.3.x? The Redlock constructor API changed a bit in 0.4, so the above wouldn't recognize your client (although that doesn't sound like this issue).

Using v0.4.0 I tried the following code with redis running on 127.0.0.1 and it worked without issue. Could you give that a shot and let me know if the issue persists?

```js
var redis = require('redis');
var Redlock = require('redlock');


var LOCK_PUBLIC_LIST = 'something';
var LOCK_TIME = 1000;

var redisClient = redis.createClient();
var redlock = new Redlock([redisClient], {
	driftFactor: 0.01,
	retryCount: 225,
	retryDelay: 250
});

redlock.lock(LOCK_PUBLIC_LIST, LOCK_TIME, function(error, lock) {
	if (error) {
		console.log(error);
	} else {
		console.log('worked')
	}
});
```

**Comment by nathansizemore** [comment]
Thanks! That would be the issue. Sorry about that, was under the impression a v0.+ bump would maintain backwards compatibility with the API.

**Comment by mike-marcacci** [comment]
Ya, you're completely right according to semver for post-1.0.0 versions. Jonathan Ong has [a great article](http://www.jongleberry.com/semver-has-failed-us.html) that addresses the wild west of pre-1.0.0 semver.

I'm contemplating following his suggestions there and skipping the 0.x.x phase in future projects, and I will probably jump to 1.0.0 for the next release of redlock. Sorry for the confusion.
