### ISSUE TITLE
Add a new method "tryLock"

### ISSUE THREAD

**Issue by jlongo-daitan** [mike-marcacci/node-redlock#52]
Add a new method "tryLock", which doesn't keep waiting for the lock

**Comment by mike-marcacci** [comment]
Is this something that could be accomplished by setting `retryCount` to `0`?

**Comment by jlongo-daitan** [comment]
If the result can tell if the lock was acquired or not, yes :)

**Comment by mike-marcacci** [comment]
@jlongo-daitan did this work for you? I'm going to close this, but feel free to reopen if this wasn't solved!
