### ISSUE TITLE
node-redlock conflits with async-redis

### ISSUE THREAD

**Issue by AndreLion** [mike-marcacci/node-redlock#53]
[node-redlock](https://github.com/mike-marcacci/node-redlock) is not working with [async-redis](https://www.npmjs.com/package/async-redis), sample code 
```
// ...do something here...
```
will never execute.

[ref](https://github.com/moaxaca/async-redis/issues/20)

**Comment by mike-marcacci** [comment]
This is expected, as redlock uses the callback API internally, which is apparently not preserved by that `async-redis`. If you want a promise API for your redis client, consider using [ioredis](https://github.com/luin/ioredis) which is far more robust, and is actually used in redlock’s tests.
