### ISSUE TITLE
Mock redlock to write unit testing

### ISSUE THREAD

**Issue by SJ-SivaSubrahmaniam** [mike-marcacci/node-redlock#54]
Hi,

I need to mock redlock to write unit testcases. npm redis-mock is not working for me. any suggestions?

**Comment by mike-marcacci** [comment]
Hi @SJ-SivaSubrahmaniam,

I would honestly just spin up a real redis server as part of your test – they are incredibly lightweight, are trivial to add using containerized workflows or are already included in most CI environments that don't use containers, and help make sure you're getting production-like results from your test.

**Comment by mike-marcacci** [comment]
Closing for now. Let me know if this didn't work for you.
