### ISSUE TITLE
2 Maintainence questions (list active locks and unlock via cli)

### ISSUE THREAD

**Issue by hkjeffchan** [mike-marcacci/node-redlock#56]
1) How to list the active locks? Tried "KEYS *" and it doesn't return the lock.

2) Just in case the lock is locked with a very big TTL and node crashed without unlock. Is it possible to unlock it via cli?

Thanks!

**Comment by mike-marcacci** [comment]
Hi @hkjeffchan,

Running `KEYS *` definitely should show all active locks, alongside any other keys in your redis instance.

Force-removing the lock is as simple as running `DEL resource_name_goes_here`, although this is definitely discouraged.

You can log locks that expire (as opposed to being released) by subscribing to redis keyspace events, like this:

```js
const client = require('ioredis').createClient(port, host, options);
client.config('set','notify-keyspace-events','Ex');
client.subscribe('__keyevent@0__:expired');
client.on('message', function(channel, message) {
    console.log({channel, message});
});
```

Hope that helps!
