### ISSUE TITLE
0 retries

### ISSUE THREAD

**Issue by elmigranto** [mike-marcacci/node-redlock#6]
It is currently not possible to ask `redlock` not to retry after failure without something like this:

``` js
  var redlock = new Redlock([redis], {retryCount: new Number(0)});
```

I understand that retrying failed lock is an important part of `distlock` algorithm, but this option might be worth adding for more simple scenarios, like 1 lock per user account to prevent user from doing things like accidental double HTTP POST on page refresh.

**Comment by elmigranto** [comment]
Possible fix can be changing `Redlock` constructor to use
``` js
this.retryCount = options.hasOwnproperty('retryCount')
  ? options.retryCount
  : defaults.retryCount;
```

instead of 

``` js
this.retryCount = options.retryCount || defaults.retryCount;
```

**Comment by mike-marcacci** [comment]
Hey @elmigranto, great catch. I've adjusted all of the options to accept any number.
