### ISSUE TITLE
It doesn't work as expected

### ISSUE THREAD

**Issue by ChoGathK** [mike-marcacci/node-redlock#61]
@mike-marcacci 
I have a local redis cluster: from 7001 to 7006

There is no problem with the normal operation of this cluster (such as set)

When I use single machine (6379), Cluster single node (7001), ioredis.cluster as parameters to pass into redlock, it is normal

But according to your demo, using an array of nodes will report an error: ReplyError: MOVED 15784 127.0.0.1:7003

However, 127.0.0.1:7003 does generate set information

Below is my code, I hope you can see and give me some Suggestions, thank you!

```js
let conf = [{
        "host": "127.0.0.1",
        "port": 6379
    }, {
        "host": "127.0.0.1",
        "port": 7001
    },
    {
        "host": "127.0.0.1",
        "port": 7002
    },
    {
        "host": "127.0.0.1",
        "port": 7003
    },
    {
        "host": "127.0.0.1",
        "port": 7004
    },
    {
        "host": "127.0.0.1",
        "port": 7005
    },
    {
        "host": "127.0.0.1",
        "port": 7006
    }
];

let ioredis = require('ioredis');
let redlock = require('redlock');

// fork
let redis = [new ioredis(conf[1])];
// array
let redisList = conf.map(e => new ioredis(e));
// cluster
let redisCluster = [new ioredis.Cluster(conf)];
// redlock
let __R = new redlock(redisList, {
    driftFactor: 0.01, // time in ms
    retryCount: 10,
    retryDelay: 200, // time in ms
    retryJitter: 200 // time in ms
});
// error
__R.on('clientError', function(err) {
    console.error(err);
    debugger
});
// lock
__R.lock("LOCK-KEYS", 1000).then((lock) => {
    debugger
    return lock.unlock()
        .then(() => {
            debugger
        })
        .catch((err) => {
            debugger
        });
});
```

**Comment by ChoGathK** [comment]
Or can I put it this way?

As long as there are unreleased locks in the cluster, the locking operation does not continue and an exception is thrown

**Comment by mike-marcacci** [comment]
Hi @ChoGathK, it appears that all nodes are part of the same cluster; is that correct? If so, you can simply pass the cluster itself to redlock:

```
let __R = new redlock([ redisCluster ], {
    driftFactor: 0.01, // time in ms
    retryCount: 10,
    retryDelay: 200, // time in ms
    retryJitter: 200 // time in ms
});
```

The redlock algorithm adds strong consistencies in failure scenarios by using multiple _independent_ nodes or clusters. Since all of these are part of the same cluster, they aren't independent from each other, and just using a single cluster should be sufficient for many scenarios (high availability, but weaker consistency guarantees during failover).

**Comment by ChoGathK** [comment]
> 嗨@ChoGathK，似乎所有节点都是同一个集群的一部分; 那是对的吗？如果是这样，您可以简单地将群集本身传递给redlock：
> 
> ```js
> 让 __R  =  新 redlock（[redisCluster]，{ 
>     driftFactor ： 0.01，//在毫秒时间 
>     RetryCount重： 10，
>     retryDelay ： 200，//在毫秒时间 
>     retryJitter ： 200  //在毫秒时间 
> }）;
> ```
> 
> redlock算法通过使用多个_独立_节点或集群在故障情形中增加了强一致性。由于所有这些都是同一群集的一部分，因此它们并不是彼此独立的，只使用单个群集应该足以满足许多场景（高可用性，但在故障转移期间保证较弱的一致性）。

i get! thank you!

**Comment by ChoGathK** [comment]
> Hi @ChoGathK, it appears that all nodes are part of the same cluster; is that correct? If so, you can simply pass the cluster itself to redlock:
> 
> ```js
> let __R = new redlock([ redisCluster ], {
>     driftFactor: 0.01, // time in ms
>     retryCount: 10,
>     retryDelay: 200, // time in ms
>     retryJitter: 200 // time in ms
> });
> ```
> 
> The redlock algorithm adds strong consistencies in failure scenarios by using multiple _independent_ nodes or clusters. Since all of these are part of the same cluster, they aren't independent from each other, and just using a single cluster should be sufficient for many scenarios (high availability, but weaker consistency guarantees during failover).

i get !   thank you !
