### ISSUE TITLE
Save lock to external store

### ISSUE THREAD

**Issue by rhlsthrm** [mike-marcacci/node-redlock#62]
Is there a way to pass around the lock object, or instantiate a new lock from some secret? My use case is to have a browser-based client use a server running this package to proxy locking/unlocking.

**Comment by mike-marcacci** [comment]
Hi @rhlsthrm, sorry for the slow response. GitHub's notifications have been just profoundly unreliable and I'm not quite sure what to do about it.

Anyhow, to answer your question, you can serialize a lock and reconstruct it [using the `Lock` constructor](https://github.com/mike-marcacci/node-redlock/blob/e90e80a611c83a6a8c16912c7c5a8c6e9d49c617/redlock.js#L92).

Issue #42 is about making this easer, which I'm totally open to.
