### ISSUE TITLE
Mechanism for Checking the status of a lock without Acquiring it?

### ISSUE THREAD

**Issue by homerlex** [mike-marcacci/node-redlock#66]
Is there any mechanism to find out if a lock is currently in place without actually acquiring the lock?

I'm playing with doing some locking.  We'll have some web clients connected to our server via websockets.  I'd like for them to be able to "poll" the status of a lock for a given resource.  A given button on their UI will be enabled/disabled based on the status of the lock.

**Comment by xaviergonz** [comment]
This would be great, I'm trying to devise a way to use redlock in a FIFO manner (so whoever asks for the lock first gets executed first).

So far I've though of this basic algorithm:
```
next = INCR counterKey
prev = next - 1
lock "next"
if prev exists block until lock "prev" is unlocked while extending next until done	
// do the task work
unlock "next"
```
but I'm missing a way to poll/block until a lock is finished without actually locking it

**Comment by mike-marcacci** [comment]
You might accomplish this simply by checking the existence of the redis key. However, you probably are better off acquiring the lock. See [here](https://github.com/mike-marcacci/node-redlock#how-do-i-check-if-something-is-locked) for a broader discussion.
