### ISSUE TITLE
Export LockError

### ISSUE THREAD

**Issue by elmigranto** [mike-marcacci/node-redlock#7]
So client code can differentiate failing to acquire the lock from other errors (like redis connectivity issues). Ability to do stuff like this would be nice:

``` js
if (err instanceof redlock.LockError) {
  // …
}
```

**Comment by mike-marcacci** [comment]
Hey @elmigranto, this is a great suggestion. Just implemented it and will publish a patch in just a few moments.

**Comment by mike-marcacci** [comment]
Just to be clear here: it's actually attached to the `Redlock` constructor, not its prototype. It can be found by doing:

```js
var Redlock = require('redlock');
console.log(Redlock.LockError);
```

**Comment by elmigranto** [comment]
Nice, thanks!
