### ISSUE TITLE
Auto extend lock

### ISSUE THREAD

**Issue by kbkesit** [mike-marcacci/node-redlock#73]
Hi, after reading documentation on npm package page, is there a way to auto extend ttl of lock, to prevent code executed outside the lock? Considering it's possible that some async work haven't finished. Thank you.

**Comment by mike-marcacci** [comment]
This is a fantastic idea, and one that I will look into implementing. I've been exceedingly busy elsewhere, but have a lot of changes planned for this library, which I hope to make shortly.

**Comment by kbkesit** [comment]
Great! Looking forward to it.

**Comment by Sytten** [comment]
Also looking forward to that, it would be super useful

**Comment by onichandame** [comment]
+1 for this feature too. Btw, I am using setInterval(()=>lock.extend(TTL), TTL/2) as a workaround

**Comment by clouedoc** [comment]
Hello, we've encountered this issue in production with long-running tasks.

We are going to fix it with a variant of @onichandame's suggestion.

## Locking code

```ts

/**
 * Return a Redlock.Lock for the given proxy ID
 * @param isTaskStillRunning a function that tells the lock if the task is still running. This is used to extend the lock
 * @param ttl the base time to live of the lock. Used for testing
 */
export async function getProxyRedlock(
  proxyId: string,
  isTaskStillRunning: () => boolean,
  ttl: number = PROXY_LOCK_TIMEOUT
): Promise<{ unlock: () => Promise<void> }> {
  const redlock = new Redlock([redisClient()], { retryCount: 1 })
  const key = getProxyLockKey(proxyId)
  const lock = await redlock.lock(key, ttl)

  // automatically extend the lock
  const extendLater = (): void => {
    setTimeout(async () => {
      const shouldExtend = isTaskStillRunning()

      if (shouldExtend) {
        let isExpired = false
        try {
          await lock.extend(ttl)
        } catch (err) {
          isExpired = err.message.includes("Cannot extend lock on resource")
          if (isExpired) {
            logger.error("The lock expired", { key })
          } else {
            throw err
          }
        }

        if (!isExpired) {
          extendLater()
        }
      }
    }, ttl / 2)
  }

  extendLater()

  return {
    unlock: async () => {
      return lock.unlock()
    }
  }
}
```

## Testing code

```ts
import { delay, uuid } from "@force-adverse/utils"
import { getProxyRedlock } from "./proxy-lock"

const testTtl = 1000

jest.setTimeout(30 * testTtl)

/**
 * Note: you should have a Redis client ready
 */
it("should not crash when unlocking after TTL", async () => {
  const lock = await getProxyRedlock(uuid(), () => true, testTtl)
  await delay(testTtl + testTtl * 5)
  await expect(lock.unlock()).resolves.not.toThrow()
})
```

**Comment by mike-marcacci** [comment]
Hi there @clouedoc – thanks for this contribution!

For everybody here: in the v5 alpha (the current `main` branch), I have [added a "using" method](https://github.com/mike-marcacci/node-redlock#usage) which wraps a routine within an auto-extending lock. This leverages the [AbortController standard](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) to communicate any extension failures into the running routine. This would be used like:

```ts
await redlock.using([senderId, recipientId], 5000, async (signal) => {
  // Do something...
  await something();

  // Make sure any necessary lock extension has not failed.
  if (signal.aborted) {
    throw signal.error;
  }

  // Do something else...
  await somethingElse();
});
```

I'm going to close this issue, but do feel free to continue discussing here if you have questions or further suggestions!
