### ISSUE TITLE
use evalsha

### ISSUE THREAD

**Issue by yosiat** [mike-marcacci/node-redlock#76]
Hi!

Currently, when executing the scripts node-redlock uses eval, is it acceptable to do a PR that will do `SCRIPT LOAD` and then will use `evalsha`?

this can help reduce network traffic to redis

**Comment by mike-marcacci** [comment]
Hi @yosiat! That would be perfectly welcome :)

**Comment by yosiat** [comment]
@mike-marcacci I see the library is not tied to specific node redis implementation.
which I should check against? ioredis only?
