### ISSUE TITLE
Naming Convention and Locking the field of a key and usage of async/await

### ISSUE THREAD

**Issue by madabhaviamit** [mike-marcacci/node-redlock#78]
Hi Team,

This is purely a question and not an issue.

I am a bit confused with the usage of resource name here, 
// the string identifier for the resource you want to lock
var resource = 'locks:account:322456';

1. In the above resource variable, is the name of the key to be locked is '**locks:account:322456**' ? if not what is the exact name of the key in the resource declaration above. Since my i have a key(which is a map) with name as ServerUsersMap and the fields are the actual server IPs. now if i want to lock the resource '**ServerUsersMap**' what naming convention i shall follow?

2. Is it possible to lock a field of a key and not the whole key? Since i only want to update the values against the field of one particular key and i would not want to lock the entire key itself.

3. Is it possible to use async/await for locking the resources? Since i would want to proceed my code execution only when i have the lock and i would not want to use the callback function.

Thanks in Advance,
Amit

**Comment by mike-marcacci** [comment]
Hi @madabhaviamit - sorry for the late reply here!

To answer your questions:

1. This library doesn't "lock keys in redis" but instead "uses redis to coordinate exclusive access to some resource". You can therefore use whatever naming convention fits your application, making sure the keys don't collide with other keys in the same redis database, if you're using it for multiple use cases.
2. As in number 1, the "key" here is really any identifier you chose, and not specific to redis.
3. Absolutely! In JS the whole async/await syntax is just "syntactic sugar" for regular old Promises, so you should be able to use it with redlock with no problems.
