### ISSUE TITLE
How to check for lock

### ISSUE THREAD

**Issue by cobolbaby** [mike-marcacci/node-redlock#79]
Is there a check method, such as `hasLock('key')` ?

**Comment by mike-marcacci** [comment]
Hi @cobolbaby, sorry for the late reply. Unfortunately, this functionality isn't quite what this package is designed to do: the problem with such a method is that it provides _almost_ no information, as a lock could be acquired milliseconds after a "no lock" response, and furthermore, when using a high-availability setup a lock "existing or not existing" is a much more involved question. Hopefully that helps!
