### ISSUE TITLE
Better/more specific error reporting?

### ISSUE THREAD

**Issue by jraede** [mike-marcacci/node-redlock#8]
I just had an issue in which we had accidentally pointed to a specific node instead of the replica set URL, and the replica set changed the primary, so we started getting `ERROR: READ-ONLY` errors. However the errors we saw from `redlock` were just `Exceeded X attempts to lock...`

It would be nice to have a debug mode or some other method of logging for if `err` is not `null` in the `loop` function. I'm happy to submit a PR - what do you think is the best approach?

**Comment by mike-marcacci** [comment]
Hey @jraede, that's a good point – I could see that being very frustrating. My preference here is probably to make redlock an event emitter, then emit an 'error' event that you could listen to and log. Would that work for you?

**Comment by jraede** [comment]
Yeah that's great.

**Comment by mike-marcacci** [comment]
Hey man, just to follow up, I decided to go with the name `clientError` for this event, as `error` has special meaning and I wanted to be clear that these weren't lock errors, but client/connection errors.

This should be available in 0.5.

**Comment by jraede** [comment]
Awesome. Much appreciated.

**Comment by mike-marcacci** [comment]
np!
