### ISSUE TITLE
Is having multiple Redlock instances wrong?

### ISSUE THREAD

**Issue by Mattesackboy** [mike-marcacci/node-redlock#87]
Is having multiple Redlock instances on a NodeJS (express) app right/safe or should I have only one instance (maybe as a JS module) and then when I need to use Redlock I just import it and use `redlock.lock(...)`?
@mike-marcacci

**Comment by mike-marcacci** [comment]
You can safely have multiple instances running within the same process, although I don't think I've seen that pattern used particularly often. Note that it's (obviously) essential that the same instantiation settings are used for each instance, particularly ensuring that all the same redis servers (of you're using many) are used.
