### ISSUE TITLE
Will RedLock still works in case there's 1 out of 3 redis is down for a long time? e.g 30mins - 1 hour

### ISSUE THREAD

**Issue by genz10** [mike-marcacci/node-redlock#88]
Question:

Will RedLock still works (able to acquire lock & release it properly) in case there's 1 out of 3 Redis is down for a long time? e.g 30mins - 1 hour

**Comment by mike-marcacci** [comment]
Hi @genz10 yes, as long as a majority of independent redis instances are available, redlock should be able to provide the same availability and exclusivity guarantees as if they were all up.
