### ISSUE TITLE
Drop LUA for Redis Native

### ISSUE THREAD

**Issue by Bajix** [mike-marcacci/node-redlock#97]
If I wrote a redis native module for this, would you adopt it and drop LUA?

**Comment by ccollie** [comment]
I'd vote no, or at least make it configurable. For people using hosted `redis` instances which they do not control (hence to which they cannot install modules), this would be a non-starter.

**Comment by Bajix** [comment]
I'm willing to write a redis native module for this if it'll be integrated as it'll be substantially faster. If you want to support both, be my guest. Do you want this or not?

**Comment by mike-marcacci** [comment]
Hi @Bajix, I definitely agree with @ccollie that the deployment requirements would be at odds with the purpose of this library. I don't have any experience writing such modules, but you might be able to add a first-class "lock" command and remove the need for language-specific library support entirely.
